name: krono
description: "A daily photo journal app to track your year, one moment at a time"
publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: '>=3.5.0 <4.0.0' # Setați pe versiunea actuală de Flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & UX
  flutter_speed_dial: ^7.0.0
  gap: ^3.0.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  url_launcher: ^6.3.2

  # State Management
  flutter_riverpod: ^3.1.0

  # Media & Files
  gal: ^2.1.1
  image_picker: ^1.0.4
  file_picker: ^10.3.8
  path_provider: ^2.1.2
  path: ^1.9.0
  archive: ^4.0.7
  image: ^4.5.4

  # Database (Drift)
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.24

  # System & Auth
  local_auth: ^3.0.0
  shared_preferences: ^2.5.4
  share_plus: ^12.0.1

  # Notifications & Background
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1

  # Utils & Exports
  intl: ^0.20.2
  http: ^1.6.0
  pdf: ^3.10.8
  printing: ^5.11.1
  flutter_image_compress: ^2.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  marquee: ^2.3.0
  permission_handler: ^12.0.1
  camera: 0.11.3
  #perfect_volume_control: ^1.0.6
  flutter_native_splash: "^2.4.0"
  visibility_detector: ^0.4.0+2
  #flutter_quill: ^11.5.0
  crypto: ^3.0.7
  sliver_tools: ^0.2.12
  #fps_monitor: ^2.0.0
  #photo_manager: ^3.8.3

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Generators
  build_runner: ^2.4.13
  #isar_generator: ^3.1.0+1

  mockito: ^5.6.3
  mocktail: ^1.0.4

  drift_dev: ^2.20.0

  # Branding
  flutter_launcher_icons: ^0.14.4

  local_auth_android: any
  local_auth_darwin: any
  local_auth_windows: any
  path_provider_platform_interface: any
  plugin_platform_interface: any
  flutter_local_notifications_platform_interface: any
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/krono.png
    - assets/icon_mono.png
    - assets/krono_splash.png
    - assets/krono_light_splash.png


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/krono.png"


  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/krono.png"

  monochrome_android_icon: "assets/icon_mono.png"

  notification_icon:
    path: "assets/icon_mono.png"
    color: "#121212"

flutter_native_splash:
  # Light mode
  color: "#F5F5F5"
  image: "assets/krono_light_splash.png"

  # Dark mode
  color_dark: "#121212"
  image_dark: "assets/krono_splash.png"

  android_12:
    # Light mode Android 12+
    color: "#FFFFFF"
    image: "assets/krono_light_splash.png"
    icon_background_color: "#FFFFFF"

    # Dark mode Android 12+
    color_dark: "#121212"
    image_dark: "assets/krono_splash.png"
    icon_background_color_dark: "#121212"

  fullscreen: true